// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8FmAzI1_Rzb8ZYOXxVoWuAbJc4KRVl0E',
    appId: '1:845438732911:web:9654c717c9be9a1c1e9b9a',
    messagingSenderId: '845438732911',
    projectId: 'alzheimer-597a2',
    authDomain: 'alzheimer-597a2.firebaseapp.com',
    storageBucket: 'alzheimer-597a2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5b1WXrnDJRRyRO15rjOthcrBgiTnqh9I',
    appId: '1:845438732911:android:6bf1f7df781da8781e9b9a',
    messagingSenderId: '845438732911',
    projectId: 'alzheimer-597a2',
    storageBucket: 'alzheimer-597a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCy_4mtQ1Ife6rs5NCmPScH-Z7ywbAtbY',
    appId: '1:845438732911:ios:72670da34eb4892c1e9b9a',
    messagingSenderId: '845438732911',
    projectId: 'alzheimer-597a2',
    storageBucket: 'alzheimer-597a2.appspot.com',
    iosBundleId: 'com.example.alheimer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCy_4mtQ1Ife6rs5NCmPScH-Z7ywbAtbY',
    appId: '1:845438732911:ios:72670da34eb4892c1e9b9a',
    messagingSenderId: '845438732911',
    projectId: 'alzheimer-597a2',
    storageBucket: 'alzheimer-597a2.appspot.com',
    iosBundleId: 'com.example.alheimer',
  );
}
